added observation invoice
giansalex/greenter-core pull request #15
Opened 2019-05-16 03:21 UTC by p3dr0tg

2019-05-18 02:00 UTC, giansalex commented
Hola @p3dr0tg , gracias por tu aporte.

2019-05-18 02:01 UTC, giansalex requested changes
Desde que el tag de `<Notes>` puede ser mas de uno, teniendo en cuenta eso observaciones tendria que ser un array de string.

2019-05-20 00:18 UTC, p3dr0tg commented
@giansalex  lo puse string porque mayormente se agrega solo una observacion en un texarea,pero podria ser un array de string

2019-05-20 17:58 UTC, giansalex approved these changes
Listo, gracias.

2019-05-20 17:58 UTC, merged